#!/usr/bin/env bash

if [ -z "$1" ] || [ -z "$2" ]; then
	echo "Usage: my-go-compile [input] [output]"
	exit 1
fi

go build \
         -trimpath \
         -buildmode=pie \
         -mod=readonly \
         -modcacherw \
         -ldflags "-linkmode external -extldflags \"-s -w\"" -o "$2" $1
